site_name: Machine Learning Tutorials (ML_train)
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: deep purple
nav:
  - Machine Learning Tutorials: index.md
  - Requirements: requirements.md
  - Supervised Learning:
    - Regression:
      - Linear Regression: linear_regression.md
    - Classification:
      - Logistic Regression: logistic_regression.md
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


repo_url: https://github.com/dgalvis/ML_train
site_url: https://dgalvis.github.io/ML_train
