site_name: Training in Machine Learning (ML_train)
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: deep purple
nav:
  - Home: index.md
  - Requirements: requirements.md


repo_url: https://github.com/dgalvis/ML_train
site_url: https://dgalvis.github.io/ML_train
