site_name: Training in Machine Learning (ML_train)
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: deep purple
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Linear Regression: linear_regression.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


repo_url: https://github.com/dgalvis/ML_train
site_url: https://dgalvis.github.io/ML_train
