name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Tiny installer + built-in caching for both the env and package downloads
      - name: Set up Micromamba (with caching)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements_test.yml   # your existing conda env file
          environment-name: ML_train_test          # name of the env to create/use
          cache-environment: true                  # cache the fully-built env
          cache-downloads: true                    # cache package downloads
          init-shell: bash                         # optional, but fine to keep

      - name: Run tests
        run: |
          cd codes
          micromamba run -n ML_train_test python -m modules.test_lin_reg

